{
 "title": "MQTT Load Simulator",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(mqtt_load_clients_current)", "legendFormat": "Clients" },
    {
     "expr": "sum(mqtt_load_clients_connected_current)",
     "legendFormat": "Connected clients"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_load_subscriptions_current)",
     "legendFormat": "Current Subscriptions"
    },
    {
     "expr": "sum(mqtt_load_subscribe_sent_total)",
     "legendFormat": "Subscribe Sent"
    },
    {
     "expr": "sum(mqtt_load_unsubscribe_sent_total)",
     "legendFormat": "Unsubscribe Sent"
    },
    {
     "expr": "sum(mqtt_load_subscriptions_disconnected_current)",
     "legendFormat": "Current subscriptions offline"
    },
    {
     "expr": "sum(mqtt_load_subscribe_failed_total)",
     "legendFormat": "Subscribe failed"
    }
   ]
  },
  {
   "title": "Publish Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_load_publish_sent_total)",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(mqtt_load_publish_sent_total[1m]))",
     "legendFormat": "rate, msg/sec"
    }
   ]
  },
  {
   "title": "Publish Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_load_publish_received_total)",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(mqtt_load_publish_received_total[1m]))",
     "legendFormat": "rate, msg/sec"
    }
   ]
  },
  {
   "title": "Connected clients by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqtt_load_clients_connected_current",
     "legendFormat": "Connected clients on {{instance}}"
    }
   ]
  },
  {
   "title": "Connection Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_load_connect_sent_total)",
     "legendFormat": "Connect sent"
    },
    {
     "expr": "sum(mqtt_load_connect_success_total)",
     "legendFormat": "Connect success"
    },
    {
     "expr": "sum(mqtt_load_connect_failures_total)",
     "legendFormat": "Connect failures"
    },
    {
     "expr": "sum(mqtt_load_disconnects_intentional_total)",
     "legendFormat": "Disconnects - intentional"
    },
    {
     "expr": "sum(mqtt_load_disconnects_total)",
     "legendFormat": "Disconnects - total"
    },
    {
     "expr": "sum(mqtt_load_connect_aborts_total)",
     "legendFormat": "Aborted connections"
    }
   ]
  },
  {
   "title": "Connect latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(quantile)(mqtt_load_connect_success_latency)",
     "legendFormat": "Success connection latency (q={{quantile}})"
    },
    {
     "expr": "sum by(quantile)(mqtt_load_connect_fail_latency)",
     "legendFormat": "Failed connection latency (q={{quantile}})"
    }
   ]
  },
  {
   "title": "Subscribe latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(quantile)(mqtt_load_subscribe_latency)",
     "legendFormat": "Subscribe latency (q={{quantile}})"
    }
   ]
  }
 ]
}