global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'simplematter-mqttd-kafka'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s

    static_configs:
      - targets: ['localhost:1884']
      #      - targets: ['94.130.13.210:1884']
