#!/bin/sh
set -e

SCRIPT_DIR=`realpath $(dirname "$0")`

#IMAGE_NAME=simplematter/simplematter-mqtt-load-simulator:0.0.8
#IMAGE_NAME=simplematter/simplematter-mqtt-load-simulator:0.0.8-SNAPSHOT
IMAGE_NAME=simplematter-mqtt-load-simulator
CONTAINER_NAME=simplematter-mqtt-load-simulator
echo Starting $CONTAINER_NAME from $IMAGE_NAME

#Specity your broker URL
MQTT_LOAD_SERVER=localhost:1883
#MQTT_LOAD_SERVER=localhost:11883

#interactive
INTERACTIVE=-it
#non-interactive
#INTERACTIVITY=-d

JMX_OPTIONS=""

DEBUG_OPTIONS=""

#No cleanup
#CLEANUP=""
#Remove container automatically when completed
CLEANUP="--rm"

#General load settings
MQTT_LOAD_CLIENT_PREFIX=simplematter-mqtt-load-simulator
MQTT_LOAD_TOPIC_PREFIX="mqtt-load-sim"

MQTT_LOAD_TOPIC_GROUPS_NUMBER=5
MQTT_LOAD_TOPICS_NUMBER=50

MQTT_LOAD_MESSAGE_MIN_SIZE=800
MQTT_LOAD_MESSAGE_MAX_SIZE=1200

#Publishing clients
MQTT_LOAD_PUBLISHING_CLIENTS_NUMBER=2
#MQTT_LOAD_PUBLISHING_CLIENTS_NUMBER=0
MQTT_LOAD_PUBLISHING_CLIENTS_MESSAGES_PER_SECOND=0.1

#Subscribing clients
MQTT_LOAD_SUBSCRIBING_CLIENTS_NUMBER=4
#MQTT_LOAD_SUBSCRIBING_CLIENTS_NUMBER=0
MQTT_LOAD_SUBSCRIBING_CLIENTS_WILDCARD_SUBSCRIPTIONS=2
MQTT_LOAD_SUBSCRIBING_CLIENTS_REGULAR_SUBSCRIPTIONS=10

#Randomized clients
#MQTT_LOAD_RANDOMIZED_CLIENTS_MIN_NUMBER=1
MQTT_LOAD_RANDOMIZED_CLIENTS_MIN_NUMBER=0
#MQTT_LOAD_RANDOMIZED_CLIENTS_MAX_NUMBER=5
MQTT_LOAD_RANDOMIZED_CLIENTS_MAX_NUMBER=0

MQTT_LOAD_RANDOMIZED_CLIENT_PUBLISH_PROBABILITY=100
MQTT_LOAD_RANDOMIZED_CLIENT_SUBSCRIBE_PROBABILITY=0
MQTT_LOAD_RANDOMIZED_CLIENT_UNSUBSCRIBE_PROBABILITY=0
MQTT_LOAD_RANDOMIZED_CLIENT_IDLE_PROBABILITY=0

MQTT_LOAD_SIMULATION_STEP_INTERVAL=2000
MQTT_LOAD_CLIENT_STEP_INTERVAL=10000
MQTT_LOAD_STATS_INTERVAL=5000

MQTT_LOAD_RAMP_UP_SECONDS=10
#MQTT_LOAD_RAMP_UP_SECONDS=30

MQTT_LOAD_ACTIONS_DURING_RAMP_UP=false

MQTT_LOAD_CONNECTION_TIMEOUT_SECONDS=30
MQTT_LOAD_KEEP_ALIVE_SECONDS=30
#MQTT_LOAD_KEEP_ALIVE_SECONDS=180
#MQTT_LOAD_MONITORING_PORT=1884
MQTT_LOAD_MONITORING_PORT=1885

docker run $INTERACTIVITY $CLEANUP $JMX_OPTIONS $DEBUG_OPTIONS \
     -e MQTT_LOAD_SERVER=$MQTT_LOAD_SERVER \
     -e MQTT_LOAD_PUBLISHING_CLIENTS_NUMBER=$MQTT_LOAD_PUBLISHING_CLIENTS_NUMBER \
     -e MQTT_LOAD_PUBLISHING_CLIENTS_MESSAGES_PER_SECOND=$MQTT_LOAD_PUBLISHING_CLIENTS_MESSAGES_PER_SECOND \
     -e MQTT_LOAD_SUBSCRIBING_CLIENTS_NUMBER=$MQTT_LOAD_SUBSCRIBING_CLIENTS_NUMBER \
     -e MQTT_LOAD_SUBSCRIBING_CLIENTS_WILDCARD_SUBSCRIPTIONS=$MQTT_LOAD_SUBSCRIBING_CLIENTS_WILDCARD_SUBSCRIPTIONS \
     -e MQTT_LOAD_SUBSCRIBING_CLIENTS_REGULAR_SUBSCRIPTIONS=$MQTT_LOAD_SUBSCRIBING_CLIENTS_REGULAR_SUBSCRIPTIONS \
     -e MQTT_LOAD_RANDOMIZED_CLIENTS_MIN_NUMBER=$MQTT_LOAD_RANDOMIZED_CLIENTS_MIN_NUMBER \
     -e MQTT_LOAD_RANDOMIZED_CLIENTS_MAX_NUMBER=$MQTT_LOAD_RANDOMIZED_CLIENTS_MAX_NUMBER \
     -e MQTT_LOAD_CLIENT_PREFIX=$MQTT_LOAD_CLIENT_PREFIX \
     -e MQTT_LOAD_TOPIC_PREFIX=$MQTT_LOAD_TOPIC_PREFIX \
     -e MQTT_LOAD_TOPICS_NUMBER=$MQTT_LOAD_TOPICS_NUMBER \
     -e MQTT_LOAD_MESSAGE_MIN_SIZE=$MQTT_LOAD_MESSAGE_MIN_SIZE \
     -e MQTT_LOAD_MESSAGE_MAX_SIZE=$MQTT_LOAD_MESSAGE_MAX_SIZE \
     -e MQTT_LOAD_RANDOMIZED_CLIENT_PUBLISH_PROBABILITY=$MQTT_LOAD_RANDOMIZED_CLIENT_PUBLISH_PROBABILITY \
     -e MQTT_LOAD_RANDOMIZED_CLIENT_SUBSCRIBE_PROBABILITY=$MQTT_LOAD_RANDOMIZED_CLIENT_SUBSCRIBE_PROBABILITY \
     -e MQTT_LOAD_RANDOMIZED_CLIENT_UNSUBSCRIBE_PROBABILITY=$MQTT_LOAD_RANDOMIZED_CLIENT_UNSUBSCRIBE_PROBABILITY \
     -e MQTT_LOAD_RANDOMIZED_CLIENT_IDLE_PROBABILITY=$MQTT_LOAD_RANDOMIZED_CLIENT_IDLE_PROBABILITY \
     -e MQTT_LOAD_SIMULATION_STEP_INTERVAL=$MQTT_LOAD_SIMULATION_STEP_INTERVAL \
     -e MQTT_LOAD_CLIENT_STEP_INTERVAL=$MQTT_LOAD_CLIENT_STEP_INTERVAL \
     -e MQTT_LOAD_STATS_INTERVAL=$MQTT_LOAD_STATS_INTERVAL \
     -e MQTT_LOAD_RAMP_UP_SECONDS=$MQTT_LOAD_RAMP_UP_SECONDS \
     -e MQTT_LOAD_ACTIONS_DURING_RAMP_UP=$MQTT_LOAD_ACTIONS_DURING_RAMP_UP \
     -e MQTT_LOAD_CONNECTION_TIMEOUT_SECONDS=$MQTT_LOAD_CONNECTION_TIMEOUT_SECONDS \
     -e MQTT_LOAD_KEEP_ALIVE_SECONDS=$MQTT_LOAD_KEEP_ALIVE_SECONDS \
     -e MQTT_LOAD_MONITORING_PORT=$MQTT_LOAD_MONITORING_PORT \
     --network host \
     --name $CONTAINER_NAME $IMAGE_NAME

