#!/bin/sh
set -e

SCRIPT_DIR=`realpath $(dirname "$0")`

CONTAINER_NAME=simplematter-mqtt-load-simulator
echo Starting $CONTAINER_NAME

#Specity your broker URL
#MQTT_LOAD_SERVER=localhost:1883
MQTT_LOAD_SERVER=localhost:11883

#interactive
INTERACTIVE=-it
#non-interactive
#INTERACTIVITY=-d

JMX_OPTIONS=""

DEBUG_OPTIONS=""

#No cleanup
#CLEANUP=""
#Remove container automatically when completed
CLEANUP="--rm"


#MQTT_LOAD_FIXED_CLIENTS=1000
MQTT_LOAD_FIXED_CLIENTS=5000
#MQTT_LOAD_FIXED_CLIENTS=10000
#MQTT_LOAD_MIN_CLIENTS=10
MQTT_LOAD_MIN_CLIENTS=$MQTT_LOAD_FIXED_CLIENTS
#MQTT_LOAD_MAX_CLIENTS=50
MQTT_LOAD_MAX_CLIENTS=$MQTT_LOAD_FIXED_CLIENTS

MQTT_LOAD_CLIENT_PREFIX=simplematter-mqtt-load-simulator
MQTT_LOAD_TOPIC_PREFIX="mqtt-load-sim/"

#MQTT_LOAD_TOPICS_NUMBER=50
MQTT_LOAD_TOPICS_NUMBER=$MQTT_LOAD_MAX_CLIENTS

MQTT_LOAD_MESSAGE_MIN_SIZE=10
MQTT_LOAD_MESSAGE_MAX_SIZE=600

#MQTT_LOAD_CLIENT_PUBLISH_PROBABILITY=25
MQTT_LOAD_CLIENT_PUBLISH_PROBABILITY=100
#MQTT_LOAD_CLIENT_SUBSCRIBE_PROBABILITY=10
MQTT_LOAD_CLIENT_SUBSCRIBE_PROBABILITY=0
#MQTT_LOAD_CLIENT_UNSUBSCRIBE_PROBABILITY=5
MQTT_LOAD_CLIENT_UNSUBSCRIBE_PROBABILITY=0
#MQTT_LOAD_CLIENT_IDLE_PROBABILITY=50
MQTT_LOAD_CLIENT_IDLE_PROBABILITY=0

MQTT_LOAD_SIMULATION_STEP_INTERVAL=2000
MQTT_LOAD_CLIENT_STEP_INTERVAL=2000
MQTT_LOAD_STATS_INTERVAL=5000

MQTT_LOAD_RAMP_UP_SECONDS=30

MQTT_LOAD_ACTIONS_DURING_RAMP_UP=false

MQTT_LOAD_CONNECTION_TIMEOUT_SECONDS=60
MQTT_LOAD_KEEP_ALIVE_SECONDS=180
#MQTT_LOAD_MONITORING_PORT=1884
MQTT_LOAD_MONITORING_PORT=1885

docker run $INTERACTIVITY $CLEANUP $JMX_OPTIONS $DEBUG_OPTIONS \
     -e MQTT_LOAD_SERVER=$MQTT_LOAD_SERVER \
     -e MQTT_LOAD_MIN_CLIENTS=$MQTT_LOAD_MIN_CLIENTS \
     -e MQTT_LOAD_MAX_CLIENTS=$MQTT_LOAD_MAX_CLIENTS \
     -e MQTT_LOAD_CLIENT_PREFIX=$MQTT_LOAD_CLIENT_PREFIX \
     -e MQTT_LOAD_TOPIC_PREFIX=$MQTT_LOAD_TOPIC_PREFIX \
     -e MQTT_LOAD_TOPICS_NUMBER=$MQTT_LOAD_TOPICS_NUMBER \
     -e MQTT_LOAD_MESSAGE_MIN_SIZE=$MQTT_LOAD_MESSAGE_MIN_SIZE \
     -e MQTT_LOAD_MESSAGE_MAX_SIZE=$MQTT_LOAD_MESSAGE_MAX_SIZE \
     -e MQTT_LOAD_CLIENT_PUBLISH_PROBABILITY=$MQTT_LOAD_CLIENT_PUBLISH_PROBABILITY \
     -e MQTT_LOAD_CLIENT_SUBSCRIBE_PROBABILITY=$MQTT_LOAD_CLIENT_SUBSCRIBE_PROBABILITY \
     -e MQTT_LOAD_CLIENT_UNSUBSCRIBE_PROBABILITY=$MQTT_LOAD_CLIENT_UNSUBSCRIBE_PROBABILITY \
     -e MQTT_LOAD_CLIENT_IDLE_PROBABILITY=$MQTT_LOAD_CLIENT_IDLE_PROBABILITY \
     -e MQTT_LOAD_SIMULATION_STEP_INTERVAL=$MQTT_LOAD_SIMULATION_STEP_INTERVAL \
     -e MQTT_LOAD_CLIENT_STEP_INTERVAL=$MQTT_LOAD_CLIENT_STEP_INTERVAL \
     -e MQTT_LOAD_STATS_INTERVAL=$MQTT_LOAD_STATS_INTERVAL \
     -e MQTT_LOAD_RAMP_UP_SECONDS=$MQTT_LOAD_RAMP_UP_SECONDS \
     -e MQTT_LOAD_ACTIONS_DURING_RAMP_UP=$MQTT_LOAD_ACTIONS_DURING_RAMP_UP \
     -e MQTT_LOAD_CONNECTION_TIMEOUT_SECONDS=$MQTT_LOAD_CONNECTION_TIMEOUT_SECONDS \
     -e MQTT_LOAD_KEEP_ALIVE_SECONDS=$MQTT_LOAD_KEEP_ALIVE_SECONDS \
     -e MQTT_LOAD_MONITORING_PORT=$MQTT_LOAD_MONITORING_PORT \
     --network host \
     --name $CONTAINER_NAME $CONTAINER_NAME

